api_namespace: knowlg-api

env:
  javaoptions: -Xmx600m

replicaCount: 1
#repository: docker.io/aimansharief/content-service-modified2
#image_tag: R5.7.0
repository: docker.io/maheshkg/content-service
image_tag: R5.7.2
resources:
  requests:
    cpu: 100m
    memory: 100Mi
  limits:
    cpu: 1
    memory: 1024Mi
network:
  port: 9000
  targetport: 9000
strategy:
  type: RollingUpdate
  maxsurge: 25%
  maxunavailable: 25%
serviceType: LoadBalancer
#cassandra_connection: cassandra-db.knowlg-db.svc.cluster.local:9042
cassandra_connection: cassandra.knowlg-db.svc.cluster.local:9042
redis_connection: redis-master.knowlg-db.svc.cluster.local
neo4j_domain_connection: neo4j.knowlg-db.svc.cluster.local:7687
neo4j_all_connection: neo4j.knowlg-db.svc.cluster.local:8687  
kafka_connection: kafka-headless.knowlg-db.svc.cluster.local:9092
collection_keyspace: dev_hierarchy_store
content_keyspace: dev_content_store
cloud_storage_env: staging
cloud_storage_content_folder: "content"
cloud_storage_asset_folder: "assets"
cloud_storage_artefact_folder: "artifact"
cloud_storage_bundle_folder: "bundle"
cloud_storage_media_folder: "media"
cloud_storage_ecar_folder: "ecar_files"
cloud_storage_upload_url_ttl: "54000"
cloudstorage_relative_path_prefix_content: CONTENT_STORAGE_BASE_PATH
cloudstorage_metadata_list: ["appIcon", "artifactUrl", "posterImage", "previewUrl", "thumbnail", "assetsMap", "certTemplate", "itemSetPreviewUrl", "grayScaleAppIcon", "sourceURL", "variants", "downloadUrl", "streamingUrl", "toc_url", "data", "question", "solutions", "editorState", "media", "pdfUrl", "transcripts"]
cloudstorage_read_base_path: "https://sunbirddevbbpublic.blob.core.windows.net"
cloudstorage_write_base_path: ["https://sunbirdstagingpublic.blob.core.windows.net", "https://sunbirddevbbpublic.blob.core.windows.net"]
schema_base_path: ${schema_base_path}
cloud_storage_type: ${cloud_storage_type}
cloud_storage_key: ${cloud_storage_key}
cloud_storage_secret: ${cloud_storage_secret}
cloud_storage_container: ${cloud_storage_container}